services:
  # Backend API
  - type: web
    name: inscription-app-api
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npx prisma generate
    startCommand: node src/index.js
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false

  # Frontend static
  - type: static # Correction ici : 'static' remplace 'web' pour les sites statiques
    name: inscription-app-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist # Désormais parfaitement valide avec le type static
